import {
  PrismaClient,
  Role,
  LeadStatus,
  LeadSource,
  DealStatus,
  Department,
  EmployeeStatus,
  AttendanceStatus,
  InvoiceStatus,
  PaymentMethod,
  IntegrationProvider,
  IntegrationStatus,
  Prisma,
} from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

/**
 * ============================================================================
 * NEXORA CRM — DEMO DATABASE SEED SCRIPT (PHASE 15 SALES CRM EXPANSION)
 * 
 * NOTE: All data generated by this seed script is strictly fictional demo data
 * for local development and demonstration purposes. No real personal or corporate
 * data is stored or represented.
 * ============================================================================
 */

async function main() {
  console.log("🌱 Starting NEXORA CRM database seed...");

  // 1. Clean existing records in dependency order
  await prisma.notificationPreference.deleteMany({});
  await prisma.auditLog.deleteMany({});
  await prisma.workspaceInvitation.deleteMany({});
  await prisma.notification.deleteMany({});
  await prisma.note.deleteMany({});
  await prisma.task.deleteMany({});
  await prisma.activity.deleteMany({});
  await prisma.deal.deleteMany({});
  await prisma.pipelineStage.deleteMany({});
  await prisma.pipeline.deleteMany({});
  await prisma.contact.deleteMany({});
  await prisma.company.deleteMany({});
  await prisma.integrationEvent.deleteMany({});
  await prisma.leadExternalIdentity.deleteMany({});
  await prisma.invoiceItem.deleteMany({});
  await prisma.invoice.deleteMany({});
  await prisma.integration.deleteMany({});
  await prisma.employee.deleteMany({});
  await prisma.lead.deleteMany({});
  await prisma.membership.deleteMany({});
  await prisma.user.deleteMany({});
  await prisma.workspace.deleteMany({});

  console.log("🧹 Cleaned existing database records.");

  // 2. Create Default Workspace
  const workspace = await prisma.workspace.create({
    data: {
      name: "Nova Real Estate & Tech Solutions",
      slug: "nova-realty",
      timezone: "Asia/Kolkata",
      currency: "INR",
      dateFormat: "DD/MM/YYYY",
    },
  });

  console.log(`🏢 Created workspace: ${workspace.name} (${workspace.id})`);

  // 3. Create Demo Users with Hashed Passwords
  const defaultPasswordHash = await bcrypt.hash("Nexora@2026", 10);

  const demoUser = await prisma.user.create({
    data: {
      name: "Alex Chen",
      email: "demo@nexora.local",
      passwordHash: defaultPasswordHash,
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    },
  });

  const rahulUser = await prisma.user.create({
    data: {
      name: "Rahul Sharma",
      email: "rahul@nexora.local",
      passwordHash: defaultPasswordHash,
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    },
  });

  const priyaUser = await prisma.user.create({
    data: {
      name: "Priya Mehta",
      email: "priya@nexora.local",
      passwordHash: defaultPasswordHash,
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    },
  });

  const amitUser = await prisma.user.create({
    data: {
      name: "Amit Verma",
      email: "amit@nexora.local",
      passwordHash: defaultPasswordHash,
    },
  });

  const ananyaUser = await prisma.user.create({
    data: {
      name: "Ananya Singh",
      email: "ananya@nexora.local",
      passwordHash: defaultPasswordHash,
    },
  });

  console.log("👥 Created demo users.");

  // 4. Create Workspace Memberships
  await prisma.membership.createMany({
    data: [
      { userId: demoUser.id, workspaceId: workspace.id, role: Role.OWNER },
      { userId: rahulUser.id, workspaceId: workspace.id, role: Role.ADMIN },
      { userId: priyaUser.id, workspaceId: workspace.id, role: Role.MANAGER },
      { userId: amitUser.id, workspaceId: workspace.id, role: Role.MEMBER },
      { userId: ananyaUser.id, workspaceId: workspace.id, role: Role.MEMBER },
    ],
  });

  // Create notification preferences
  await prisma.notificationPreference.createMany({
    data: [
      { userId: demoUser.id },
      { userId: rahulUser.id },
      { userId: priyaUser.id },
      { userId: amitUser.id },
      { userId: ananyaUser.id },
    ],
  });

  console.log("🎟️ Created workspace memberships & notification preferences.");

  // 5. Create Multiple Pipelines and Stages
  const salesPipeline = await prisma.pipeline.create({
    data: {
      workspaceId: workspace.id,
      name: "Sales Pipeline",
      isDefault: true,
      stages: {
        create: [
          { workspaceId: workspace.id, name: "New", order: 0, probability: 10, color: "#3B82F6" },
          { workspaceId: workspace.id, name: "Qualified", order: 1, probability: 25, color: "#6366F1" },
          { workspaceId: workspace.id, name: "Demo", order: 2, probability: 50, color: "#8B5CF6" },
          { workspaceId: workspace.id, name: "Proposal", order: 3, probability: 70, color: "#F59E0B" },
          { workspaceId: workspace.id, name: "Negotiation", order: 4, probability: 85, color: "#0EA5E9" },
          { workspaceId: workspace.id, name: "Won", order: 5, probability: 100, color: "#10B981" },
          { workspaceId: workspace.id, name: "Lost", order: 6, probability: 0, color: "#EF4444" },
        ],
      },
    },
    include: { stages: { orderBy: { order: "asc" } } },
  });

  const enterprisePipeline = await prisma.pipeline.create({
    data: {
      workspaceId: workspace.id,
      name: "Enterprise Pipeline",
      isDefault: false,
      stages: {
        create: [
          { workspaceId: workspace.id, name: "Discovery", order: 0, probability: 15, color: "#3B82F6" },
          { workspaceId: workspace.id, name: "Technical Review", order: 1, probability: 35, color: "#6366F1" },
          { workspaceId: workspace.id, name: "Proof of Concept", order: 2, probability: 60, color: "#8B5CF6" },
          { workspaceId: workspace.id, name: "Commercial Proposal", order: 3, probability: 75, color: "#F59E0B" },
          { workspaceId: workspace.id, name: "Legal & Security", order: 4, probability: 90, color: "#0EA5E9" },
          { workspaceId: workspace.id, name: "Won", order: 5, probability: 100, color: "#10B981" },
          { workspaceId: workspace.id, name: "Lost", order: 6, probability: 0, color: "#EF4444" },
        ],
      },
    },
    include: { stages: { orderBy: { order: "asc" } } },
  });

  console.log("📊 Created multi-pipeline models & stages.");

  // 6. Create 5 Realistic Companies
  const acmeRealty = await prisma.company.create({
    data: {
      workspaceId: workspace.id,
      name: "Acme Realty",
      website: "https://acmerealty.in",
      industry: "Real Estate Development",
      phone: "+91 22 2847 1100",
      email: "corporate@acmerealty.in",
      address: "Bandra Kurla Complex, Mumbai, Maharashtra",
      ownerId: rahulUser.id,
    },
  });

  const techNova = await prisma.company.create({
    data: {
      workspaceId: workspace.id,
      name: "TechNova",
      website: "https://technova.io",
      industry: "B2B SaaS & Cloud",
      phone: "+91 80 4122 3344",
      email: "sales@technova.io",
      address: "Indiranagar, Bengaluru, Karnataka",
      ownerId: priyaUser.id,
    },
  });

  const globalProperties = await prisma.company.create({
    data: {
      workspaceId: workspace.id,
      name: "Global Properties",
      website: "https://globalproperties.com",
      industry: "Commercial Brokerage",
      phone: "+91 124 456 7890",
      email: "info@globalproperties.com",
      address: "Golf Course Road, Gurgaon, Haryana",
      ownerId: demoUser.id,
    },
  });

  const bluePeak = await prisma.company.create({
    data: {
      workspaceId: workspace.id,
      name: "BluePeak",
      website: "https://bluepeakcapital.com",
      industry: "Fintech & Asset Management",
      phone: "+91 22 6677 8899",
      email: "connect@bluepeakcapital.com",
      address: "Nariman Point, Mumbai, Maharashtra",
      ownerId: rahulUser.id,
    },
  });

  const novaEnterprises = await prisma.company.create({
    data: {
      workspaceId: workspace.id,
      name: "Nova Enterprises",
      website: "https://novaenterprises.in",
      industry: "Supply Chain & Logistics",
      phone: "+91 79 2654 3210",
      email: "operations@novaenterprises.in",
      address: "SG Highway, Ahmedabad, Gujarat",
      ownerId: amitUser.id,
    },
  });

  console.log("🏢 Created 5 demo companies.");

  // 7. Create 10 Contacts
  const contact1 = await prisma.contact.create({
    data: {
      workspaceId: workspace.id,
      firstName: "Vikram",
      lastName: "Malhotra",
      email: "vikram.m@acmerealty.in",
      phone: "+91 98201 44521",
      jobTitle: "Chief Investment Officer",
      companyId: acmeRealty.id,
      ownerId: rahulUser.id,
    },
  });

  const contact2 = await prisma.contact.create({
    data: {
      workspaceId: workspace.id,
      firstName: "Sunita",
      lastName: "Rao",
      email: "sunita.rao@technova.io",
      phone: "+91 98450 11234",
      jobTitle: "VP Technology",
      companyId: techNova.id,
      ownerId: priyaUser.id,
    },
  });

  const contact3 = await prisma.contact.create({
    data: {
      workspaceId: workspace.id,
      firstName: "Rajesh",
      lastName: "Khandelwal",
      email: "rajesh@novaenterprises.in",
      phone: "+91 97110 88921",
      jobTitle: "Managing Director",
      companyId: novaEnterprises.id,
      ownerId: amitUser.id,
    },
  });

  const contact4 = await prisma.contact.create({
    data: {
      workspaceId: workspace.id,
      firstName: "Meera",
      lastName: "Krishnan",
      email: "meera.k@technova.io",
      phone: "+91 99002 33451",
      jobTitle: "Director of Product",
      companyId: techNova.id,
      ownerId: ananyaUser.id,
    },
  });

  const contact5 = await prisma.contact.create({
    data: {
      workspaceId: workspace.id,
      firstName: "Kabir",
      lastName: "Sengupta",
      email: "kabir@globalproperties.com",
      phone: "+91 98310 99401",
      jobTitle: "Head of Acquisitions",
      companyId: globalProperties.id,
      ownerId: demoUser.id,
    },
  });

  const contact6 = await prisma.contact.create({
    data: {
      workspaceId: workspace.id,
      firstName: "Tanya",
      lastName: "Kapoor",
      email: "tanya.k@bluepeakcapital.com",
      phone: "+91 98101 77239",
      jobTitle: "Senior Portfolio Manager",
      companyId: bluePeak.id,
      ownerId: rahulUser.id,
    },
  });

  const contact7 = await prisma.contact.create({
    data: {
      workspaceId: workspace.id,
      firstName: "Siddharth",
      lastName: "Nambiar",
      email: "sid.nambiar@acmerealty.in",
      phone: "+91 94470 66321",
      jobTitle: "Procurement Lead",
      companyId: acmeRealty.id,
      ownerId: priyaUser.id,
    },
  });

  const contact8 = await prisma.contact.create({
    data: {
      workspaceId: workspace.id,
      firstName: "Deepak",
      lastName: "Choudhury",
      email: "deepak.c@technova.io",
      phone: "+91 98230 45190",
      jobTitle: "Enterprise Architect",
      companyId: techNova.id,
      ownerId: rahulUser.id,
    },
  });

  const contact9 = await prisma.contact.create({
    data: {
      workspaceId: workspace.id,
      firstName: "Alia",
      lastName: "Merchant",
      email: "alia.m@bluepeakcapital.com",
      phone: "+91 98200 12389",
      jobTitle: "COO",
      companyId: bluePeak.id,
      ownerId: demoUser.id,
    },
  });

  const contact10 = await prisma.contact.create({
    data: {
      workspaceId: workspace.id,
      firstName: "Arun",
      lastName: "Swaminathan",
      email: "arun.s@globalproperties.com",
      phone: "+91 94440 88312",
      jobTitle: "VP Commercial Leasing",
      companyId: globalProperties.id,
      ownerId: demoUser.id,
    },
  });

  console.log("👤 Created 10 demo contacts.");

  // Helper date generators
  const now = new Date();
  const nextMonth = new Date(now.getFullYear(), now.getMonth() + 1, 15);
  const inTwoMonths = new Date(now.getFullYear(), now.getMonth() + 2, 20);
  const inThreeMonths = new Date(now.getFullYear(), now.getMonth() + 3, 28);
  const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 10);

  const sStages = salesPipeline.stages;
  const eStages = enterprisePipeline.stages;

  // 8. Create 20 Realistic Deals (Open, Won, Lost)
  const dealsData = [
    // Won Deals
    {
      name: "Enterprise CRM & PMS Rollout",
      companyId: techNova.id,
      contactId: contact2.id,
      ownerId: priyaUser.id,
      ownerName: "Priya Mehta",
      pipelineId: salesPipeline.id,
      stageId: sStages[5].id, // Won
      value: new Prisma.Decimal(6400000),
      probability: 100,
      status: DealStatus.WON,
      wonAt: lastMonth,
      source: LeadSource.WEBSITE,
      description: "Full enterprise CRM deployment across 4 regional delivery hubs.",
    },
    {
      name: "3BHK Luxury Tower Sales Automation",
      companyId: acmeRealty.id,
      contactId: contact1.id,
      ownerId: rahulUser.id,
      ownerName: "Rahul Sharma",
      pipelineId: salesPipeline.id,
      stageId: sStages[5].id, // Won
      value: new Prisma.Decimal(8200000),
      probability: 100,
      status: DealStatus.WON,
      wonAt: lastMonth,
      source: LeadSource.HOUSING,
      description: "Automated booking engine and CRM for Phase 1 luxury units.",
    },
    {
      name: "Annual Cloud Infrastructure Contract",
      companyId: globalProperties.id,
      contactId: contact5.id,
      ownerId: demoUser.id,
      ownerName: "Alex Chen",
      pipelineId: enterprisePipeline.id,
      stageId: eStages[5].id, // Won
      value: new Prisma.Decimal(4500000),
      probability: 100,
      status: DealStatus.WON,
      wonAt: now,
      source: LeadSource.WEBSITE,
      description: "High-availability multi-tenant cloud tenancy and support.",
    },
    // Lost Deals
    {
      name: "Fleet Telematics Integration",
      companyId: novaEnterprises.id,
      contactId: contact3.id,
      ownerId: amitUser.id,
      ownerName: "Amit Verma",
      pipelineId: salesPipeline.id,
      stageId: sStages[6].id, // Lost
      value: new Prisma.Decimal(1250000),
      probability: 0,
      status: DealStatus.LOST,
      lostAt: lastMonth,
      lostReason: "Price",
      source: LeadSource.INDIAMART,
      description: "Client selected lower-tier budget vendor.",
    },
    {
      name: "Fintech Compliance Portal",
      companyId: bluePeak.id,
      contactId: contact6.id,
      ownerId: rahulUser.id,
      ownerName: "Rahul Sharma",
      pipelineId: enterprisePipeline.id,
      stageId: eStages[6].id, // Lost
      value: new Prisma.Decimal(3500000),
      probability: 0,
      status: DealStatus.LOST,
      lostAt: now,
      lostReason: "Competitor",
      source: LeadSource.WEBSITE,
      description: "Lost to incumbent provider offering bundled services.",
    },
    // Open Deals (High, Medium, Early probabilities)
    {
      name: "Website Redesign & Lead Pipeline",
      companyId: acmeRealty.id,
      contactId: contact7.id,
      ownerId: priyaUser.id,
      ownerName: "Priya Mehta",
      pipelineId: salesPipeline.id,
      stageId: sStages[4].id, // Negotiation
      value: new Prisma.Decimal(2800000),
      probability: 85,
      status: DealStatus.OPEN,
      expectedCloseDate: nextMonth,
      source: LeadSource.WEBSITE,
      description: "Interactive 3D unit selector and dynamic brochure builder.",
    },
    {
      name: "HRMS Deployment & Attendance Sync",
      companyId: techNova.id,
      contactId: contact4.id,
      ownerId: ananyaUser.id,
      ownerName: "Ananya Singh",
      pipelineId: salesPipeline.id,
      stageId: sStages[4].id, // Negotiation
      value: new Prisma.Decimal(1950000),
      probability: 85,
      status: DealStatus.OPEN,
      expectedCloseDate: nextMonth,
      source: LeadSource.FACEBOOK,
      description: "Biometric API sync and automated payroll processing.",
    },
    {
      name: "Commercial Grade-A Leasing System",
      companyId: globalProperties.id,
      contactId: contact10.id,
      ownerId: demoUser.id,
      ownerName: "Alex Chen",
      pipelineId: enterprisePipeline.id,
      stageId: eStages[4].id, // Legal & Security
      value: new Prisma.Decimal(7500000),
      probability: 90,
      status: DealStatus.OPEN,
      expectedCloseDate: inTwoMonths,
      source: LeadSource.NINETY_NINE_ACRES,
      description: "Commercial lease ledger and tenant billing portal.",
    },
    {
      name: "Wealth Advisory Omni-Channel CRM",
      companyId: bluePeak.id,
      contactId: contact9.id,
      ownerId: demoUser.id,
      ownerName: "Alex Chen",
      pipelineId: salesPipeline.id,
      stageId: sStages[3].id, // Proposal
      value: new Prisma.Decimal(5200000),
      probability: 70,
      status: DealStatus.OPEN,
      expectedCloseDate: nextMonth,
      source: LeadSource.WEBSITE,
      description: "WhatsApp Business API and automated portfolio alerts.",
    },
    {
      name: "Cold Chain Warehouse Logistics Engine",
      companyId: novaEnterprises.id,
      contactId: contact3.id,
      ownerId: amitUser.id,
      ownerName: "Amit Verma",
      pipelineId: salesPipeline.id,
      stageId: sStages[3].id, // Proposal
      value: new Prisma.Decimal(3100000),
      probability: 70,
      status: DealStatus.OPEN,
      expectedCloseDate: inTwoMonths,
      source: LeadSource.INDIAMART,
      description: "Real-time temperature logging and SLA breach notifications.",
    },
    {
      name: "Retail CRM & Loyalty Rewards Engine",
      companyId: techNova.id,
      contactId: contact2.id,
      ownerId: priyaUser.id,
      ownerName: "Priya Mehta",
      pipelineId: salesPipeline.id,
      stageId: sStages[2].id, // Demo
      value: new Prisma.Decimal(2400000),
      probability: 50,
      status: DealStatus.OPEN,
      expectedCloseDate: inTwoMonths,
      source: LeadSource.GOOGLE_ADS,
      description: "Multi-tier loyalty points and SMS engagement triggers.",
    },
    {
      name: "Enterprise Architecture Consultation",
      companyId: techNova.id,
      contactId: contact8.id,
      ownerId: rahulUser.id,
      ownerName: "Rahul Sharma",
      pipelineId: enterprisePipeline.id,
      stageId: eStages[2].id, // Proof of Concept
      value: new Prisma.Decimal(4200000),
      probability: 60,
      status: DealStatus.OPEN,
      expectedCloseDate: inThreeMonths,
      source: LeadSource.WEBSITE,
      description: "POC for microservices migration and event streaming.",
    },
    {
      name: "Smart Billing & GST E-Invoicing Bridge",
      companyId: acmeRealty.id,
      contactId: contact1.id,
      ownerId: rahulUser.id,
      ownerName: "Rahul Sharma",
      pipelineId: salesPipeline.id,
      stageId: sStages[1].id, // Qualified
      value: new Prisma.Decimal(1800000),
      probability: 25,
      status: DealStatus.OPEN,
      expectedCloseDate: inTwoMonths,
      source: LeadSource.WEBSITE,
      description: "Direct NIC portal integration for e-way bills and IRN generation.",
    },
    {
      name: "Lead Ingestion Connectors Suite",
      companyId: globalProperties.id,
      contactId: contact5.id,
      ownerId: ananyaUser.id,
      ownerName: "Ananya Singh",
      pipelineId: salesPipeline.id,
      stageId: sStages[1].id, // Qualified
      value: new Prisma.Decimal(950000),
      probability: 25,
      status: DealStatus.OPEN,
      expectedCloseDate: nextMonth,
      source: LeadSource.FACEBOOK,
      description: "Multi-portal webhook bridge from 99acres and Housing.com.",
    },
    {
      name: "Global Property Portfolio Dashboard",
      companyId: globalProperties.id,
      contactId: contact10.id,
      ownerId: demoUser.id,
      ownerName: "Alex Chen",
      pipelineId: enterprisePipeline.id,
      stageId: eStages[1].id, // Technical Review
      value: new Prisma.Decimal(5800000),
      probability: 35,
      status: DealStatus.OPEN,
      expectedCloseDate: inThreeMonths,
      source: LeadSource.WEBSITE,
      description: "Executive analytics aggregating cross-border property yield.",
    },
    {
      name: "Private Equity LP Reporting Suite",
      companyId: bluePeak.id,
      contactId: contact6.id,
      ownerId: rahulUser.id,
      ownerName: "Rahul Sharma",
      pipelineId: enterprisePipeline.id,
      stageId: eStages[0].id, // Discovery
      value: new Prisma.Decimal(6900000),
      probability: 15,
      status: DealStatus.OPEN,
      expectedCloseDate: inThreeMonths,
      source: LeadSource.WEBSITE,
      description: "Automated quarterly LP distribution statements and NAV logs.",
    },
    {
      name: "Warehouse Yard Management System",
      companyId: novaEnterprises.id,
      contactId: contact3.id,
      ownerId: amitUser.id,
      ownerName: "Amit Verma",
      pipelineId: salesPipeline.id,
      stageId: sStages[0].id, // New
      value: new Prisma.Decimal(1650000),
      probability: 10,
      status: DealStatus.OPEN,
      expectedCloseDate: inTwoMonths,
      source: LeadSource.INDIAMART,
      description: "Dock scheduling and gate pass verification system.",
    },
    {
      name: "Commercial Broker Commission Tracker",
      companyId: globalProperties.id,
      contactId: contact5.id,
      ownerId: priyaUser.id,
      ownerName: "Priya Mehta",
      pipelineId: salesPipeline.id,
      stageId: sStages[0].id, // New
      value: new Prisma.Decimal(880000),
      probability: 10,
      status: DealStatus.OPEN,
      expectedCloseDate: nextMonth,
      source: LeadSource.WEBSITE,
      description: "Commission split rules and agent payout ledger.",
    },
    {
      name: "Digital Signature & Stamp Duty Workflow",
      companyId: acmeRealty.id,
      contactId: contact7.id,
      ownerId: rahulUser.id,
      ownerName: "Rahul Sharma",
      pipelineId: salesPipeline.id,
      stageId: sStages[0].id, // New
      value: new Prisma.Decimal(1100000),
      probability: 10,
      status: DealStatus.OPEN,
      expectedCloseDate: inTwoMonths,
      source: LeadSource.WEBSITE,
      description: "Aadhaar eSign and state stamp duty payment gateway.",
    },
    {
      name: "Customer Support Helpdesk & AI Chat",
      companyId: techNova.id,
      contactId: contact4.id,
      ownerId: ananyaUser.id,
      ownerName: "Ananya Singh",
      pipelineId: salesPipeline.id,
      stageId: sStages[0].id, // New
      value: new Prisma.Decimal(1450000),
      probability: 10,
      status: DealStatus.OPEN,
      expectedCloseDate: inTwoMonths,
      source: LeadSource.GOOGLE_ADS,
      description: "Omni-channel ticket routing and automated FAQ bot.",
    },
  ];

  for (const dealData of dealsData) {
    const createdDeal = await prisma.deal.create({
      data: {
        workspaceId: workspace.id,
        name: dealData.name,
        companyId: dealData.companyId,
        contactId: dealData.contactId,
        ownerId: dealData.ownerId,
        ownerName: dealData.ownerName,
        pipelineId: dealData.pipelineId,
        stageId: dealData.stageId,
        value: dealData.value,
        probability: dealData.probability,
        status: dealData.status,
        wonAt: dealData.wonAt || null,
        lostAt: dealData.lostAt || null,
        lostReason: dealData.lostReason || null,
        expectedCloseDate: dealData.expectedCloseDate || null,
        source: dealData.source,
        description: dealData.description,
      },
    });

    // Create activity on each deal
    await prisma.activity.create({
      data: {
        workspaceId: workspace.id,
        dealId: createdDeal.id,
        companyId: dealData.companyId,
        contactId: dealData.contactId,
        userId: dealData.ownerId,
        type: dealData.status === DealStatus.WON ? "deal_won" : dealData.status === DealStatus.LOST ? "deal_lost" : "deal_created",
        title: dealData.status === DealStatus.WON ? "Deal Closed Won 🎉" : dealData.status === DealStatus.LOST ? `Deal Lost: ${dealData.lostReason}` : "Opportunity Initialized",
        description: `Deal "${dealData.name}" valued at ₹${Number(dealData.value).toLocaleString("en-IN")}`,
        author: dealData.ownerName,
      },
    });
  }

  console.log("💼 Created 20 demo deals with activities across stages and pipelines.");

  // 9. Create 15 Inbound Realistic Leads (Some Converted, Some Open)
  const leadsData = [
    {
      name: "Vikram Malhotra",
      company: "Acme Realty",
      email: "vikram.m@acmerealty.in",
      phone: "+91 98201 44521",
      source: LeadSource.NINETY_NINE_ACRES,
      status: LeadStatus.WON,
      ownerName: "Rahul Sharma",
      ownerId: rahulUser.id,
      value: new Prisma.Decimal(8200000),
      isConverted: true,
      convertedAt: lastMonth,
      convertedCompanyId: acmeRealty.id,
      convertedContactId: contact1.id,
      tags: JSON.stringify(["Commercial", "High-Priority", "Mumbai"]),
      notes: "Lead converted into Acme Realty corporate account.",
    },
    {
      name: "Sunita Rao",
      company: "TechNova",
      email: "sunita.rao@technova.io",
      phone: "+91 98450 11234",
      source: LeadSource.WEBSITE,
      status: LeadStatus.WON,
      ownerName: "Priya Mehta",
      ownerId: priyaUser.id,
      value: new Prisma.Decimal(6400000),
      isConverted: true,
      convertedAt: lastMonth,
      convertedCompanyId: techNova.id,
      convertedContactId: contact2.id,
      tags: JSON.stringify(["Healthcare", "Enterprise", "Bengaluru"]),
      notes: "Converted into TechNova SaaS deployment deal.",
    },
    {
      name: "Rajesh Khandelwal",
      company: "Nova Enterprises",
      email: "rajesh@novaenterprises.in",
      phone: "+91 97110 88921",
      source: LeadSource.INDIAMART,
      status: LeadStatus.QUALIFIED,
      ownerName: "Amit Verma",
      ownerId: amitUser.id,
      value: new Prisma.Decimal(1250000),
      isConverted: true,
      convertedAt: now,
      convertedCompanyId: novaEnterprises.id,
      convertedContactId: contact3.id,
      tags: JSON.stringify(["Logistics", "Inbound", "Ahmedabad"]),
      notes: "Fleet automation consultation scheduled.",
    },
    {
      name: "Meera Krishnan",
      company: "TechNova",
      email: "meera.k@technova.io",
      phone: "+91 99002 33451",
      source: LeadSource.FACEBOOK,
      status: LeadStatus.QUALIFIED,
      ownerName: "Ananya Singh",
      ownerId: ananyaUser.id,
      value: new Prisma.Decimal(2900000),
      tags: JSON.stringify(["Retail", "Omnichannel", "Chennai"]),
      notes: "Demo completed. High probability prospect.",
    },
    {
      name: "Kabir Sengupta",
      company: "Global Properties",
      email: "kabir@globalproperties.com",
      phone: "+91 98310 99401",
      source: LeadSource.HOUSING,
      status: LeadStatus.WON,
      ownerName: "Alex Chen",
      ownerId: demoUser.id,
      value: new Prisma.Decimal(4500000),
      isConverted: true,
      convertedAt: now,
      convertedCompanyId: globalProperties.id,
      convertedContactId: contact5.id,
      tags: JSON.stringify(["Real Estate", "Won Deal", "Gurgaon"]),
      notes: "Contract executed for portfolio cloud rollout.",
    },
    {
      name: "Tanya Kapoor",
      company: "BluePeak",
      email: "tanya.k@bluepeakcapital.com",
      phone: "+91 98101 77239",
      source: LeadSource.GOOGLE_ADS,
      status: LeadStatus.NEW,
      ownerName: "Rahul Sharma",
      ownerId: rahulUser.id,
      value: new Prisma.Decimal(750000),
      tags: JSON.stringify(["Fintech", "SME", "Delhi"]),
      notes: "Lead captured via Google Search Ads campaign.",
    },
    {
      name: "Siddharth Nambiar",
      company: "Acme Realty",
      email: "sid.nambiar@acmerealty.in",
      phone: "+91 94470 66321",
      source: LeadSource.INDIAMART,
      status: LeadStatus.CONTACTED,
      ownerName: "Priya Mehta",
      ownerId: priyaUser.id,
      value: new Prisma.Decimal(1800000),
      tags: JSON.stringify(["Procurement", "Mumbai"]),
      notes: "First discovery call scheduled for next week.",
    },
    {
      name: "Deepak Choudhury",
      company: "TechNova",
      email: "deepak.c@technova.io",
      phone: "+91 98230 45190",
      source: LeadSource.WEBSITE,
      status: LeadStatus.PROPOSAL,
      ownerName: "Rahul Sharma",
      ownerId: rahulUser.id,
      value: new Prisma.Decimal(4500000),
      tags: JSON.stringify(["Cloud", "B2B SaaS", "Pune"]),
      notes: "Technical proposal and architecture diagram submitted.",
    },
    {
      name: "Alia Merchant",
      company: "BluePeak",
      email: "alia.m@bluepeakcapital.com",
      phone: "+91 98200 12389",
      source: LeadSource.FACEBOOK,
      status: LeadStatus.QUALIFIED,
      ownerName: "Alex Chen",
      ownerId: demoUser.id,
      value: new Prisma.Decimal(3200000),
      tags: JSON.stringify(["Luxury", "WhatsApp CRM", "Mumbai"]),
      notes: "High intent buyer seeking WhatsApp API automation.",
    },
    {
      name: "Arun Swaminathan",
      company: "Global Properties",
      email: "arun.s@globalproperties.com",
      phone: "+91 94440 88312",
      source: LeadSource.WEBSITE,
      status: LeadStatus.NEGOTIATION,
      ownerName: "Alex Chen",
      ownerId: demoUser.id,
      value: new Prisma.Decimal(5800000),
      tags: JSON.stringify(["Energy", "Enterprise", "Chennai"]),
      notes: "Commercial terms sent. Reviewing with legal counsel.",
    },
    {
      name: "Pooja Deshmukh",
      company: "Prime Urban Homes",
      email: "pooja.d@primeurban.in",
      phone: "+91 98220 55431",
      source: LeadSource.NINETY_NINE_ACRES,
      status: LeadStatus.NEW,
      ownerName: "Amit Verma",
      ownerId: amitUser.id,
      value: new Prisma.Decimal(2100000),
      tags: JSON.stringify(["Residential", "Inbound", "Nagpur"]),
      notes: "Buyer inquiry for 4-tower builder CRM package.",
    },
    {
      name: "Karan Joharilal",
      company: "Apex Gems & Diamonds",
      email: "karan@apexgems.com",
      phone: "+91 98210 99881",
      source: LeadSource.WHATSAPP,
      status: LeadStatus.CONTACTED,
      ownerName: "Ananya Singh",
      ownerId: ananyaUser.id,
      value: new Prisma.Decimal(1600000),
      tags: JSON.stringify(["Jewellery", "High-Net-Worth", "Surat"]),
      notes: "Contacted via WhatsApp Official Business account.",
    },
  ];

  for (const lData of leadsData) {
    const createdLead = await prisma.lead.create({
      data: {
        workspaceId: workspace.id,
        name: lData.name,
        company: lData.company,
        email: lData.email,
        phone: lData.phone,
        source: lData.source,
        status: lData.status,
        ownerName: lData.ownerName,
        ownerId: lData.ownerId,
        value: lData.value,
        isConverted: lData.isConverted || false,
        convertedAt: lData.convertedAt || null,
        convertedCompanyId: lData.convertedCompanyId || null,
        convertedContactId: lData.convertedContactId || null,
        tags: lData.tags,
        notes: lData.notes,
      },
    });

    await prisma.activity.create({
      data: {
        workspaceId: workspace.id,
        leadId: createdLead.id,
        userId: lData.ownerId,
        type: lData.isConverted ? "lead_converted" : "lead_created",
        title: lData.isConverted ? "Lead Converted" : "Lead Ingested",
        description: `Lead from ${lData.company} (${lData.source})`,
        author: lData.ownerName,
      },
    });
  }

  console.log("📋 Created demo leads with conversion history.");

  // 10. Create Employees
  await prisma.employee.createMany({
    data: [
      {
        workspaceId: workspace.id,
        name: "Alex Chen",
        email: "alex@nexora.local",
        phone: "+91 98200 11111",
        department: Department.SALES,
        role: "Head of Sales",
        status: EmployeeStatus.ACTIVE,
        attendance: AttendanceStatus.PRESENT,
        location: "Mumbai HQ",
        leaveBalance: 16,
        dealsClosed: 24,
        revenueGenerated: new Prisma.Decimal(18500000),
      },
      {
        workspaceId: workspace.id,
        name: "Rahul Sharma",
        email: "rahul@nexora.local",
        phone: "+91 98200 22222",
        department: Department.SALES,
        role: "Senior Enterprise Lead",
        status: EmployeeStatus.ACTIVE,
        attendance: AttendanceStatus.PRESENT,
        location: "Mumbai HQ",
        leaveBalance: 18,
        dealsClosed: 19,
        revenueGenerated: new Prisma.Decimal(14200000),
      },
      {
        workspaceId: workspace.id,
        name: "Priya Mehta",
        email: "priya@nexora.local",
        phone: "+91 98200 33333",
        department: Department.SALES,
        role: "Client Success Manager",
        status: EmployeeStatus.ACTIVE,
        attendance: AttendanceStatus.PRESENT,
        location: "Bengaluru Hub",
        leaveBalance: 14,
        dealsClosed: 15,
        revenueGenerated: new Prisma.Decimal(11800000),
      },
      {
        workspaceId: workspace.id,
        name: "Amit Verma",
        email: "amit@nexora.local",
        phone: "+91 98200 44444",
        department: Department.OPERATIONS,
        role: "Operations Specialist",
        status: EmployeeStatus.ACTIVE,
        attendance: AttendanceStatus.REMOTE,
        location: "Ahmedabad Hub",
        leaveBalance: 20,
        dealsClosed: 8,
        revenueGenerated: new Prisma.Decimal(4500000),
      },
      {
        workspaceId: workspace.id,
        name: "Ananya Singh",
        email: "ananya@nexora.local",
        phone: "+91 98200 55555",
        department: Department.SALES,
        role: "Inbound Sales Associate",
        status: EmployeeStatus.ACTIVE,
        attendance: AttendanceStatus.PRESENT,
        location: "Delhi NCR",
        leaveBalance: 21,
        dealsClosed: 11,
        revenueGenerated: new Prisma.Decimal(7200000),
      },
    ],
  });

  console.log("💼 Created demo employees.");

  // 11. Create Invoices (Phase 16)
  const inv1 = await prisma.invoice.create({
    data: {
      workspaceId: workspace.id,
      invoiceNumber: "INV-2026-0001",
      customerName: "Sunita Rao",
      customerCompany: "TechNova",
      customerEmail: "sunita.rao@technova.io",
      customerGst: "27AABCT3518Q1ZQ",
      status: InvoiceStatus.PAID,
      subtotal: new Prisma.Decimal(101694.92),
      discount: new Prisma.Decimal(0),
      discountType: "FIXED",
      tax: new Prisma.Decimal(18305.08),
      taxRate: new Prisma.Decimal(18),
      cgst: new Prisma.Decimal(9152.54),
      sgst: new Prisma.Decimal(9152.54),
      igst: new Prisma.Decimal(0),
      total: new Prisma.Decimal(120000.0),
      amountPaid: new Prisma.Decimal(120000.0),
      balanceDue: new Prisma.Decimal(0),
      issueDate: lastMonth,
      dueDate: now,
      paidAt: lastMonth,
      paymentMethod: "BANK_TRANSFER",
      ownerId: demoUser.id,
      ownerName: "Alex Chen",
      items: {
        create: [
          {
            description: "Enterprise CRM & Pipeline License (Annual)",
            quantity: 1,
            unitPrice: new Prisma.Decimal(101694.92),
            taxRate: new Prisma.Decimal(18),
            amount: new Prisma.Decimal(101694.92),
          },
        ],
      },
      payments: {
        create: [
          {
            workspaceId: workspace.id,
            amount: new Prisma.Decimal(120000.0),
            paymentDate: lastMonth,
            paymentMethod: PaymentMethod.BANK_TRANSFER,
            reference: "NEFT-IN-9921448",
            notes: "Full settlement received",
            recordedById: demoUser.id,
          },
        ],
      },
    },
  });

  const inv2 = await prisma.invoice.create({
    data: {
      workspaceId: workspace.id,
      invoiceNumber: "INV-2026-0002",
      customerName: "Rahul Sharma",
      customerCompany: "Acme Realty",
      customerEmail: "rahul.sharma@acmerealty.in",
      customerGst: "27AAACA9921K1ZM",
      status: InvoiceStatus.PARTIALLY_PAID,
      subtotal: new Prisma.Decimal(72033.9),
      discount: new Prisma.Decimal(0),
      discountType: "FIXED",
      tax: new Prisma.Decimal(12966.1),
      taxRate: new Prisma.Decimal(18),
      cgst: new Prisma.Decimal(6483.05),
      sgst: new Prisma.Decimal(6483.05),
      igst: new Prisma.Decimal(0),
      total: new Prisma.Decimal(85000.0),
      amountPaid: new Prisma.Decimal(40000.0),
      balanceDue: new Prisma.Decimal(45000.0),
      issueDate: now,
      dueDate: nextMonth,
      paymentMethod: "UPI",
      ownerId: amitUser.id,
      ownerName: "Amit Verma",
      items: {
        create: [
          {
            description: "Sales Lead Automation Setup",
            quantity: 1,
            unitPrice: new Prisma.Decimal(72033.9),
            taxRate: new Prisma.Decimal(18),
            amount: new Prisma.Decimal(72033.9),
          },
        ],
      },
      payments: {
        create: [
          {
            workspaceId: workspace.id,
            amount: new Prisma.Decimal(40000.0),
            paymentDate: now,
            paymentMethod: PaymentMethod.UPI,
            reference: "UPI-TXN-88412",
            notes: "Initial advance received",
            recordedById: amitUser.id,
          },
        ],
      },
    },
  });

  const inv3 = await prisma.invoice.create({
    data: {
      workspaceId: workspace.id,
      invoiceNumber: "INV-2026-0003",
      customerName: "Priya Nair",
      customerCompany: "Global Properties",
      customerEmail: "priya.nair@globalprop.com",
      status: InvoiceStatus.OVERDUE,
      subtotal: new Prisma.Decimal(211864.41),
      discount: new Prisma.Decimal(0),
      discountType: "FIXED",
      tax: new Prisma.Decimal(38135.59),
      taxRate: new Prisma.Decimal(18),
      cgst: new Prisma.Decimal(19067.8),
      sgst: new Prisma.Decimal(19067.8),
      igst: new Prisma.Decimal(0),
      total: new Prisma.Decimal(250000.0),
      amountPaid: new Prisma.Decimal(0),
      balanceDue: new Prisma.Decimal(250000.0),
      issueDate: lastMonth,
      dueDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days overdue
      ownerId: demoUser.id,
      ownerName: "Alex Chen",
      items: {
        create: [
          {
            description: "Enterprise CRM Multi-user Deployment",
            quantity: 1,
            unitPrice: new Prisma.Decimal(211864.41),
            taxRate: new Prisma.Decimal(18),
            amount: new Prisma.Decimal(211864.41),
          },
        ],
      },
    },
  });

  const inv4 = await prisma.invoice.create({
    data: {
      workspaceId: workspace.id,
      invoiceNumber: "INV-2026-0004",
      customerName: "Rohan Gupta",
      customerCompany: "BluePeak",
      customerEmail: "rohan.g@bluepeak.tech",
      status: InvoiceStatus.DRAFT,
      subtotal: new Prisma.Decimal(42372.88),
      discount: new Prisma.Decimal(0),
      discountType: "FIXED",
      tax: new Prisma.Decimal(7627.12),
      taxRate: new Prisma.Decimal(18),
      cgst: new Prisma.Decimal(3813.56),
      sgst: new Prisma.Decimal(3813.56),
      igst: new Prisma.Decimal(0),
      total: new Prisma.Decimal(50000.0),
      amountPaid: new Prisma.Decimal(0),
      balanceDue: new Prisma.Decimal(50000.0),
      issueDate: now,
      dueDate: nextMonth,
      ownerId: demoUser.id,
      ownerName: "Alex Chen",
      items: {
        create: [
          {
            description: "Custom Webhook Integrations",
            quantity: 1,
            unitPrice: new Prisma.Decimal(42372.88),
            taxRate: new Prisma.Decimal(18),
            amount: new Prisma.Decimal(42372.88),
          },
        ],
      },
    },
  });

  console.log("🧾 Created demo invoices with Phase 16 domain models.");

  // 12. Create Integrations
  await prisma.integration.createMany({
    data: [
      {
        workspaceId: workspace.id,
        provider: IntegrationProvider.FACEBOOK,
        status: IntegrationStatus.CONNECTED,
        defaultOwnerId: demoUser.id,
        defaultOwnerName: "Alex Chen",
        leadsSyncedToday: 14,
        totalSynced: 342,
        lastSync: new Date(),
      },
      {
        workspaceId: workspace.id,
        provider: IntegrationProvider.INDIAMART,
        status: IntegrationStatus.CONNECTED,
        defaultOwnerId: amitUser.id,
        defaultOwnerName: "Amit Verma",
        leadsSyncedToday: 8,
        totalSynced: 189,
        lastSync: new Date(),
      },
      {
        workspaceId: workspace.id,
        provider: IntegrationProvider.NINETY_NINE_ACRES,
        status: IntegrationStatus.CONNECTED,
        defaultOwnerId: rahulUser.id,
        defaultOwnerName: "Rahul Sharma",
        leadsSyncedToday: 21,
        totalSynced: 512,
        lastSync: new Date(),
      },
      {
        workspaceId: workspace.id,
        provider: IntegrationProvider.WHATSAPP,
        status: IntegrationStatus.CONNECTED,
        defaultOwnerId: ananyaUser.id,
        defaultOwnerName: "Ananya Singh",
        leadsSyncedToday: 5,
        totalSynced: 94,
        lastSync: new Date(),
      },
    ],
  });

  console.log("🔗 Created demo integrations.");

  // 13. Create Audit Logs
  await prisma.auditLog.createMany({
    data: [
      {
        workspaceId: workspace.id,
        userId: demoUser.id,
        action: "WORKSPACE_CREATED",
        entityType: "WORKSPACE",
        entityId: workspace.id,
        metadata: JSON.stringify({ name: workspace.name, slug: workspace.slug }),
        createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
      },
      {
        workspaceId: workspace.id,
        userId: rahulUser.id,
        action: "LEAD_CONVERTED",
        entityType: "LEAD",
        metadata: JSON.stringify({ leadName: "Vikram Malhotra", companyName: "Acme Realty", dealValue: 8200000 }),
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
      },
      {
        workspaceId: workspace.id,
        userId: priyaUser.id,
        action: "DEAL_WON",
        entityType: "DEAL",
        metadata: JSON.stringify({ dealName: "Enterprise CRM & PMS Rollout", value: 6400000 }),
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      },
      {
        workspaceId: workspace.id,
        userId: rahulUser.id,
        action: "DEAL_STAGE_CHANGED",
        entityType: "DEAL",
        metadata: JSON.stringify({ dealName: "Wealth Advisory Omni-Channel CRM", fromStage: "Demo", toStage: "Proposal" }),
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
    ],
  });

  console.log("📜 Created audit logs.");
  console.log("✅ Seed completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Error during seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
