import { Employee } from "./types";

export const INITIAL_DEMO_EMPLOYEES: Employee[] = [
  {
    id: "emp-1",
    name: "Alex Chen",
    initials: "AC",
    department: "Sales",
    role: "VP of Global Sales",
    email: "alex.chen@nexora.io",
    phone: "+91 98200 11223",
    status: "Active",
    attendance: "Present",
    location: "Mumbai HQ",
    joinDate: "2023-01-15",
    leaveBalance: 18,
    dealsClosed: 42,
    revenueGenerated: "₹48.6L",
  },
  {
    id: "emp-2",
    name: "Amit Verma",
    initials: "AV",
    department: "Sales",
    role: "Senior Account Executive",
    email: "amit.v@nexora.io",
    phone: "+91 98201 22334",
    status: "Active",
    attendance: "Present",
    location: "Mumbai HQ",
    joinDate: "2023-06-01",
    leaveBalance: 12,
    dealsClosed: 28,
    revenueGenerated: "₹24.8L",
  },
  {
    id: "emp-3",
    name: "Neha Kapoor",
    initials: "NK",
    department: "Sales",
    role: "Inbound SDR Lead",
    email: "neha.k@nexora.io",
    phone: "+91 98202 33445",
    status: "Active",
    attendance: "Remote",
    location: "Bengaluru",
    joinDate: "2024-02-10",
    leaveBalance: 14,
    dealsClosed: 19,
    revenueGenerated: "₹16.2L",
  },
  {
    id: "emp-4",
    name: "Rohan Das",
    initials: "RD",
    department: "Sales",
    role: "Account Executive",
    email: "rohan.d@nexora.io",
    phone: "+91 98203 44556",
    status: "Active",
    attendance: "Present",
    location: "Delhi NCR",
    joinDate: "2024-05-18",
    leaveBalance: 16,
    dealsClosed: 14,
    revenueGenerated: "₹11.4L",
  },
  {
    id: "emp-5",
    name: "Dr. Vikram Seth",
    initials: "VS",
    department: "Engineering",
    role: "Principal Architect",
    email: "vikram.s@nexora.io",
    phone: "+91 98204 55667",
    status: "Active",
    attendance: "Remote",
    location: "Pune",
    joinDate: "2022-11-01",
    leaveBalance: 20,
  },
  {
    id: "emp-6",
    name: "Ananya Deshmukh",
    initials: "AD",
    department: "Engineering",
    role: "Senior Fullstack Engineer",
    email: "ananya.d@nexora.io",
    phone: "+91 98205 66778",
    status: "Active",
    attendance: "Present",
    location: "Mumbai HQ",
    joinDate: "2023-08-15",
    leaveBalance: 11,
  },
  {
    id: "emp-7",
    name: "Sunita Nambiar",
    initials: "SN",
    department: "HR",
    role: "Head of People & Culture",
    email: "sunita.n@nexora.io",
    phone: "+91 98206 77889",
    status: "Active",
    attendance: "Present",
    location: "Mumbai HQ",
    joinDate: "2023-03-20",
    leaveBalance: 15,
  },
  {
    id: "emp-8",
    name: "Rajesh Kulkarni",
    initials: "RK",
    department: "Finance",
    role: "Controller & Invoicing Lead",
    email: "rajesh.k@nexora.io",
    phone: "+91 98207 88990",
    status: "Active",
    attendance: "On Leave",
    location: "Mumbai HQ",
    joinDate: "2023-04-10",
    leaveBalance: 9,
  },
];

export const DEMO_HRMS_STATS = {
  totalEmployees: 128,
  presentToday: 116,
  onLeave: 8,
  remote: 24,
};

