import { Invoice } from "./types";

export const INITIAL_DEMO_INVOICES: Invoice[] = [
  {
    id: "inv-1",
    invoiceNumber: "INV-1048",
    customerName: "Rahul Sharma",
    customerCompany: "Acme Realty Private Limited",
    customerEmail: "billing@acmerealty.in",
    customerGst: "27AADCB2230M1Z2",
    issueDate: "2026-04-12",
    dueDate: "2026-04-26",
    status: "Paid",
    paymentMethod: "HDFC Direct Bank Transfer",
    paidAt: "2026-04-13",
    items: [
      {
        id: "item-1",
        description: "NEXORA CRM Enterprise License (10 Seats, Annual)",
        quantity: 1,
        unitPrice: 120000,
        amount: 120000,
      },
      {
        id: "item-2",
        description: "Custom WhatsApp & Meta Lead Routing Onboarding",
        quantity: 1,
        unitPrice: 25000,
        amount: 25000,
      },
    ],
    subtotal: 145000,
    taxGst: 26100, // 18% GST
    total: 171100,
  },
  {
    id: "inv-2",
    invoiceNumber: "INV-1049",
    customerName: "Ananya Singh",
    customerCompany: "Apex Interior Architecture",
    customerEmail: "accounts@apexdesigns.com",
    customerGst: "29AABCA8891N1ZG",
    issueDate: "2026-04-10",
    dueDate: "2026-04-24",
    status: "Paid",
    paymentMethod: "Razorpay UPI",
    paidAt: "2026-04-11",
    items: [
      {
        id: "item-3",
        description: "NEXORA Growth Tier (5 Seats, Semi-Annual)",
        quantity: 1,
        unitPrice: 48000,
        amount: 48000,
      },
      {
        id: "item-4",
        description: "HRMS Attendance Biometric Module",
        quantity: 1,
        unitPrice: 12000,
        amount: 12000,
      },
    ],
    subtotal: 60000,
    taxGst: 10800,
    total: 70800,
  },
  {
    id: "inv-3",
    invoiceNumber: "INV-1050",
    customerName: "Vikram Sen",
    customerCompany: "CloudScale Infotech",
    customerEmail: "finance@cloudscale.io",
    customerGst: "33AAACL1902K1ZV",
    issueDate: "2026-04-08",
    dueDate: "2026-04-22",
    status: "Pending",
    items: [
      {
        id: "item-5",
        description: "NEXORA Scale License (50 Seats, Annual Sync)",
        quantity: 1,
        unitPrice: 280000,
        amount: 280000,
      },
      {
        id: "item-6",
        description: "Dedicated Slack Support Channel & SLA",
        quantity: 1,
        unitPrice: 40000,
        amount: 40000,
      },
    ],
    subtotal: 320000,
    taxGst: 57600,
    total: 377600,
  },
  {
    id: "inv-4",
    invoiceNumber: "INV-1051",
    customerName: "Rohan Malhotra",
    customerCompany: "Nova Logistics & Supply",
    customerEmail: "billing@novalogistics.in",
    customerGst: "07AAACN5542P1Z0",
    issueDate: "2026-03-25",
    dueDate: "2026-04-08",
    status: "Overdue",
    items: [
      {
        id: "item-7",
        description: "Lead Routing Webhooks & API Integration Pack",
        quantity: 1,
        unitPrice: 65000,
        amount: 65000,
      },
    ],
    subtotal: 65000,
    taxGst: 11700,
    total: 76700,
  },
  {
    id: "inv-5",
    invoiceNumber: "INV-1052",
    customerName: "Sneha Patil",
    customerCompany: "BluePeak Pharma Distribution",
    customerEmail: "accounts@bluepeakpharma.com",
    customerGst: "27AABCB9902M1Z1",
    issueDate: "2026-04-14",
    dueDate: "2026-04-28",
    status: "Pending",
    items: [
      {
        id: "item-8",
        description: "NEXORA Enterprise Platform On-Premise Gateway",
        quantity: 1,
        unitPrice: 180000,
        amount: 180000,
      },
    ],
    subtotal: 180000,
    taxGst: 32400,
    total: 212400,
  },
];

export const DEMO_INVOICE_STATS = {
  totalInvoiced: "₹42.8L",
  paid: "₹31.4L",
  pending: "₹8.2L",
  overdue: "₹3.2L",
};

