import { Lead } from "./types";

export const INITIAL_DEMO_LEADS: Lead[] = [
  {
    id: "lead-1",
    name: "Rahul Sharma",
    company: "Acme Realty Private Limited",
    email: "rahul.sharma@acmerealty.in",
    phone: "+91 98201 44521",
    source: "IndiaMART",
    status: "Qualified",
    owner: "Amit Verma",
    value: "₹1,20,000",
    valueNumeric: 120000,
    lastActivity: "10m ago",
    createdAt: "2026-04-10",
    tags: ["High Value", "Commercial", "Priority"],
    notes: "Looking to deploy CRM for their 25-agent commercial sales team across Mumbai & Pune.",
    activities: [
      {
        id: "act-1",
        type: "captured",
        title: "Lead captured via IndiaMART connector",
        description: "Inquiry received for Commercial Real Estate CRM Suite.",
        timestamp: "2 hours ago",
        author: "System Bot",
      },
      {
        id: "act-2",
        type: "call",
        title: "Discovery Call Completed",
        description: "Discussed multi-branch permissions, WhatsApp lead routing, and GST invoicing.",
        timestamp: "45m ago",
        author: "Amit Verma",
      },
      {
        id: "act-3",
        type: "status_change",
        title: "Moved to Qualified Stage",
        description: "BANT qualification passed. Budget approved for Q2.",
        timestamp: "10m ago",
        author: "Amit Verma",
      },
    ],
  },
  {
    id: "lead-2",
    name: "Priya Mehta",
    company: "Urban Homes Developers",
    email: "priya@urbanhomes.co",
    phone: "+91 98112 87340",
    source: "Facebook",
    status: "New",
    owner: "Neha Kapoor",
    value: "₹85,000",
    valueNumeric: 85000,
    lastActivity: "25m ago",
    createdAt: "2026-04-12",
    tags: ["Inbound", "Residential"],
    notes: "Interested in automating Facebook instant form leads directly to sales reps.",
    activities: [
      {
        id: "act-4",
        type: "captured",
        title: "Lead captured via Meta Instant Forms",
        description: "Ad Campaign: 'Luxury Villa Pre-launch Phase 2'.",
        timestamp: "25m ago",
        author: "System Bot",
      },
    ],
  },
  {
    id: "lead-3",
    name: "Vikram Sen",
    company: "CloudScale Infotech",
    email: "v.sen@cloudscale.io",
    phone: "+91 97410 99231",
    source: "Website",
    status: "Proposal",
    owner: "Alex Chen",
    value: "₹3,40,000",
    valueNumeric: 340000,
    lastActivity: "1h ago",
    createdAt: "2026-04-05",
    tags: ["Enterprise", "SaaS", "Annual Contract"],
    notes: "Enterprise deployment for 120 seats with custom webhook integration.",
    activities: [
      {
        id: "act-5",
        type: "captured",
        title: "Website Demo Form Submission",
        description: "Requested enterprise tier architecture consultation.",
        timestamp: "Apr 05, 2026",
        author: "Website Forms",
      },
      {
        id: "act-6",
        type: "meeting",
        title: "Executive Product Walkthrough",
        description: "Demonstrated HRMS attendance sync and GST invoice automation.",
        timestamp: "Apr 08, 2026",
        author: "Alex Chen",
      },
      {
        id: "act-7",
        type: "status_change",
        title: "Proposal Delivered",
        description: "Sent formal proposal with SLA terms for ₹3.4L annual billing.",
        timestamp: "1h ago",
        author: "Alex Chen",
      },
    ],
  },
  {
    id: "lead-4",
    name: "Rohan Malhotra",
    company: "Nova Logistics & Supply",
    email: "rohan@novalogistics.in",
    phone: "+91 99870 12345",
    source: "Google Ads",
    status: "Negotiation",
    owner: "Amit Verma",
    value: "₹1,95,000",
    valueNumeric: 195000,
    lastActivity: "2h ago",
    createdAt: "2026-04-02",
    tags: ["Logistics", "Contract Review"],
    notes: "Reviewing final contract terms. Decision expected by end of week.",
    activities: [
      {
        id: "act-8",
        type: "captured",
        title: "Google Search Ad Inbound",
        description: "Keyword: 'best crm for logistics company india'.",
        timestamp: "Apr 02, 2026",
        author: "Google Ads",
      },
      {
        id: "act-9",
        type: "status_change",
        title: "Contract Negotiation Initiated",
        description: "Custom payment terms discussed (50% upfront, 50% milestone).",
        timestamp: "2h ago",
        author: "Amit Verma",
      },
    ],
  },
  {
    id: "lead-5",
    name: "Ananya Singh",
    company: "Apex Interior Architecture",
    email: "ananya@apexdesigns.com",
    phone: "+91 98450 67890",
    source: "WhatsApp",
    status: "Won",
    owner: "Neha Kapoor",
    value: "₹95,000",
    valueNumeric: 95000,
    lastActivity: "3h ago",
    createdAt: "2026-04-01",
    tags: ["Closed Won", "Design", "Fast Close"],
    notes: "Onboarded and invoice #INV-1049 generated.",
    activities: [
      {
        id: "act-10",
        type: "captured",
        title: "WhatsApp Business Inquiry",
        description: "Direct message to sales WhatsApp bot.",
        timestamp: "Apr 01, 2026",
        author: "WhatsApp Bot",
      },
      {
        id: "act-11",
        type: "status_change",
        title: "Deal Closed & Won 🎉",
        description: "Payment verified via HDFC Direct Transfer.",
        timestamp: "3h ago",
        author: "Neha Kapoor",
      },
    ],
  },
  {
    id: "lead-6",
    name: "Karan Johar",
    company: "Prestige Heights Towers",
    email: "karan@prestigeheights.in",
    phone: "+91 98765 43210",
    source: "99acres",
    status: "Contacted",
    owner: "Rohan Das",
    value: "₹2,10,000",
    valueNumeric: 210000,
    lastActivity: "4h ago",
    createdAt: "2026-04-11",
    tags: ["Property", "Site Visits"],
    notes: "Needs automated SMS triggers sent to prospective home buyers after site visits.",
    activities: [
      {
        id: "act-12",
        type: "captured",
        title: "99acres Portal Integration",
        description: "Property Lead: Luxury 3BHK Sector 62.",
        timestamp: "Apr 11, 2026",
        author: "99acres Connector",
      },
    ],
  },
  {
    id: "lead-7",
    name: "Sneha Patil",
    company: "BluePeak Pharma Distribution",
    email: "sneha.p@bluepeakpharma.com",
    phone: "+91 98220 54321",
    source: "Custom API",
    status: "Qualified",
    owner: "Alex Chen",
    value: "₹4,50,000",
    valueNumeric: 450000,
    lastActivity: "5h ago",
    createdAt: "2026-04-07",
    tags: ["Pharma", "ERP Sync"],
    notes: "Requires custom SAP webhook integration for inventory checking.",
    activities: [
      {
        id: "act-13",
        type: "captured",
        title: "Custom REST API Endpoint",
        description: "Inbound webhook from internal dealer portal.",
        timestamp: "Apr 07, 2026",
        author: "API Webhook",
      },
    ],
  },
  {
    id: "lead-8",
    name: "Devendra Rao",
    company: "Matrix Media Advertising",
    email: "devendra@matrixmedia.co",
    phone: "+91 99000 88776",
    source: "Housing",
    status: "New",
    owner: "Rohan Das",
    value: "₹65,000",
    valueNumeric: 65000,
    lastActivity: "6h ago",
    createdAt: "2026-04-12",
    tags: ["Agency", "Fast Response"],
    notes: "Lead intake from housing partner campaign.",
    activities: [
      {
        id: "act-14",
        type: "captured",
        title: "Housing.com Campaign Sync",
        description: "Lead ID #HOU-88291 automatically mapped.",
        timestamp: "6h ago",
        author: "Housing Connector",
      },
    ],
  },
];
